### ISSUE TITLE
RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/THCTensorCopy.cu:204

### ISSUE THREAD

**Issue by linmoxiaomo** [princewang1994/RFCN_CoupleNet.pytorch#14]
I met this error when I run this code. 

Loading pretrained weights from data/pretrain_model/resnet101.pth
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/THCTensorCopy.cu line=204 error=8 : invalid device function
Traceback (most recent call last):
  File "/home/WXL/MMW/RFCN_CoupleNet.pytorch-master/trainval_net.py", line 328, in <module>
    rois_label = model(im_data, im_info, gt_boxes, num_boxes)
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/WXL/MMW/RFCN_CoupleNet.pytorch-master/lib/model/couplenet/couplenet.py", line 100, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/WXL/MMW/RFCN_CoupleNet.pytorch-master/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/WXL/MMW/RFCN_CoupleNet.pytorch-master/lib/model/rpn/proposal_layer.py", line 149, in forward
    keep_idx_i = keep_idx_i.long().view(-1)
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/tensor.py", line 51, in long
    return self.type(type(self).__module__ + '.LongTensor')
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/cuda/__init__.py", line 370, in type
    return super(_CudaBase, self).type(*args, **kwargs)
  File "/home/pzl/anaconda3/envs/torch03WXL/lib/python3.6/site-packages/torch/_utils.py", line 38, in _type
    return new_type(self.size()).copy_(self, async)
RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/THCTensorCopy.cu:204

I re-compile mask.sh, but it doesn't work.
This is my envs: torch=0.3.0, cuda=0.8
![image](https://user-images.githubusercontent.com/30820534/92547075-a837f380-f286-11ea-9bda-2cfeb0e0c2a6.png)

**Comment by linmoxiaomo** [comment]
pytorch=0.3.0, cuda=8.0, GTX 1080Ti, 
When I set CUDA_ARCH="-gencode arch=compute_61,code=sm_61", I met error "cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1". It cannot compile successfully. 
If I change  CUDA_ARCH="-gencode arch=compute_52,code=sm_52", it compiled successfully. But when I run code, another error occurs, that is "RuntimeError: cuda runtime error (8) : invalid device function at /opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/THCTensorCopy.cu:204"
